### ISSUE TITLE
Final CSS Todo List

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#184]
- [x] Animate result page
- [x] convert buttons for quiz table and admin table
- [x] Members Admin table layout to match other tables
- [x] ability to go back to module from:
    - [x] quiz members 
    - [x] module members admin
    - [x] leaderboard
- [x]  headers for module trophies and medal tables on module page
- [x]  trophy and joining live quiz section for students to be transparent. 
- [x] Pop Up when a student submit's an answer needs CSS work
- [x] Clean up mobile version

**Comment by sohilpandya** [comment]
- quiz history changes 
- header to quiz history and members as smaller header
- icon change


- add finish review button when lecturer is reviewing the quiz

- leaderboard header alignment and removal of decimal points
