### ISSUE TITLE
Server-Side Authentication using hapi-auth-jwt2

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#247]
Keeping in mind that the application will be used by a number of students who enjoy tinkering and seeing if they can benevolently 'hack' applications, a review the current application's security state will need to be carried out, with particular attention paid to:
+ [ ] Ensuring data privacy
+ [ ] Safety of URLs (i.e. ensuring a user can't just guess at a URL containing someone else's data and be able to access it)
+ [ ] Database cannot be accessible, either for viewing (data privacy) or altering of data

1 day of our security expert (@tonydaly)'s time will then be dedicated to supporting the implementation of the conclusions of this exercise.

@stianr Please add any other particular concerns to the list!

**Comment by shouston3** [comment]
Chrome settings: log http request in settings.
`httpie.org` similar to `curl` but nicer
Tony, walked through the app without looking at the code, here are the findings:

- post request to save-user using httpie
  - is_lecturer can be set to true and this allows the user to become a lecturer
  - so check is_lecturer on the server-side
- get request also has a similar issue when you send a curl request.

**Do not trust what a client sends**

Try to encode an object that contains all the information that is needed when making requests. 
  - This can then be used on every endpoint by decoding the cookie. 


**API**
Not very Resstful.

**Comment by tonydaly** [comment]
@sohilpandya @shouston3 @franzmoro one of thing I'm not sure I mentioned, is that all of this needs to be done over `https`, otherwise the initial username and password can be snooped and that invalidates everything else.

I noticed that the current Heroku app does work with https (but I believe this is because Heroku has their own SSL cert for apps on the herokuapp.com domain), but the application still needs to force all requests to be done via SSL (using something like this https://github.com/bendrucker/hapi-require-https).

**Comment by shouston3** [comment]
Thanks @tonydaly, that makes sense

@sohilpandya and I will look at implementing that in #300

**Comment by iteles** [comment]
Closing this technical issue as all issues that came out of it have now been completed 👍
