### ISSUE TITLE
Setup Authentication - server side

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#284]
After having a chat with @tonydaly #247 we'll be going down the route of using `hapi-auth-jwt2` for security

- 🆗  We've initially started our research #277 and setup the basic auth using jwt2.
- 🆗  We have also set up redis to use with caching of tokens #279 

**Todo**

- [x] set the user information as an encoded JWT cookie
- [x] setup a `logout` endpoint
- [x] Fix all the failing tests
- [x] in front end if `401` redirect user out.
- [x] revisit all endpoints and use decoded JWT rather than parameters
  - [x] remove passing all params from frontend to backend, all information should be in encoded cookie.

**Things to consider**
@shouston3 has a suggestion of changing the architecture of the endpoints to make it restful, This would potentially happen at the same time as revisiting endpoints for use with decoded JWT. #283

We will be starting with the first 3 points before tackling the endpoints. @iteles is that something we can tackle with this? 

I think the estimate for tackling all the above without the re-factor is around **3 Days** & a potential additional day if we were to include #283.

Please let us know your thoughts with regards to us tackling #283.

**Comment by iteles** [comment]
👍  Closing this technical issue, resolved as per the above 👍
