### ISSUE TITLE
Lecturers should be able to categorise questions

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#295]
As a lecturer, I would like to add one of the following categories to any questions I choose so that I can later provide more targeted feedback to students and perform more detailed analysis tasks.

<hr/>

Agreed in our workshop that these would be hard-coded for now but will need to be editable by super admins in future so please take this into account.

**Comment by iteles** [comment]
More detail on the categories given by @stianr below (taken from this [issue comment](https://github.com/cul-2016/quiz/issues/296#issuecomment-270904882)):
+ Factual: (Who did ... / In what year ... / How many ...)
+ Conceptual: (According to Theory X, what...)
+ Application: (If a car containing a helium balloon accelerates, in which direction does the balloon move? / After playing a nasty character on TV an actor receives death threats. What theory might account for that? / A patient present with the following symptoms ....)

**Comment by sohilpandya** [comment]
**Solution:** 
- Create a categories table, which to start off with will only have 3 categories. Each category will be given a category_id
-This will then be added to the questions table as an extra column called category_id. (with a relationship) 
- This future-proofs this concept as well

**Todo**
- [ ] create a new table in db
- [ ] link this to questions table under a column (category_id)
- [ ] update the saving/editing of questions in server-side so that the database adds the category to each question. (i.e. when saving a question, it should contain the new category_id in the payload to save in the database)
- [ ] update the UI so that questions can be given one of the categories using a drop-down

**Comment by shouston3** [comment]
Also ensure that the `/getQuestion` endpoint so that it serves up the categories associated with the question.
