### ISSUE TITLE
Refactor Endpoints to use data from JWT rather than query params

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#302]
Related to #284 

We need to go through all the endpoints both in the front end and back end and remove the use of query parameters for database calls and instead use the decoded token. 

**Todo**
- [x] Go through individual axios calls in the front end and remove the unnecessary params
  - `user_id`, `is_lecturer` from the params. This should be taken from the decoded token instead.
- [x] Refactor the server-side endpoints to take the `user_id` from the token instead of params.

**Comment by sohilpandya** [comment]
Example for `get-module-list` 

- [ ] update axios request
```js
axios.get(`/get-module-list?user_id=${userID}&is_lecturer=${is_lecturer}`) => axios.get(`/get-module-list`)
```
  - remove any unwanted consts from the file
- [ ] Verify the JWT Token from the cookie
```js
{ user_details:
   { user_id: 2,
     email: 'lecturer@city.ac.uk',
     is_lecturer: true,
     username: 'lecturer',
     is_verified: true,
     verification_code: null,
     reset_password_code: null,
     expiry_code: null },
  uid: '8f0176c0-d67e-11e6-846c-6fb15b0661f2',
  iat: 1483974973 }
```
  - Replace the query params with the information from the decoded token in `get-module-list` endpoint
- [ ] Update the endpoint/auth tests for backend 
- [ ] Update the Async Action tests if required for frontend

**Comment by sohilpandya** [comment]
**Update:** 
- I have pushed up the changes that refactor all the endpoints inside of `plugins/modules.js`

**Comment by sohilpandya** [comment]
I have also gone through the `plugins/users.js` and patched all the routes that were using user information from the query params to use information from the decoded token instead. 

- [x] modules.js
- [x] users.js
- [ ] quizzes.js (waiting on @shouston3 to get back, once he has completed this, then we are ready to create a PR)

**issue** - currently the circleCI is failing as a lot of tests are returning a 401/500 error, unsure why this is happening as all the tests are passing locally, potentially look at it first thing in the morning. :)
https://circleci.com/gh/cul-2016/quiz/531?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by sohilpandya** [comment]
Completed in #310 👍
