### ISSUE TITLE
Add/Edit/Run Surveys

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#322]
I'll be continuing on the PR that Franz started work in PR #286. 

**Todo**
- [x] Review all the work done by Franz
- [x] Add Surveys
  - This has been implemented, but a few minor issues in terms of UI and potential calls to server need to be looked at
- [x] Link the Survey_table up correctly
  - At the moment we have wired up the buttons in the survey table to the existing quiz request. This need to be updated.

I'll update the todo list as and when I complete the items above.

**Comment by sohilpandya** [comment]
`edit-survey`
- [ ] create root for edit-survey
- [ ] fetch survey details from db and display in the form (pre-fill it)
- [ ] Save the edited survey (endpoint)

**Comment by sohilpandya** [comment]
Currently debugging `/update-quiz` endpoint that Franz has re-architectured to get it working again with edit-survey and edit-quiz

**Comment by sohilpandya** [comment]
`run-survey`
- [ ] keep it the same as running the live quiz
- [ ] Only difference being that when the student finishes the quiz, they are taken back to module home-page and not to the final-score screen for the given Survey (as survey's do not have a scoring system)

**Comment by sohilpandya** [comment]
**update**

- [ ] Issue with editing a survey with no questionts - returns a `500` Thisissue doesn't exist with editing quiz only with surveys.

**Comment by sohilpandya** [comment]
**update**
- Lecturer flow is complete, they are able to add/edit and run a survey. 

Moving only Student's view. 
- [ ] update `save-student-response`
- [ ] when survey is complete take students to module dashboard instead of score

**Comment by shouston3** [comment]
Really nice work @sohilpandya

**Comment by sohilpandya** [comment]
@shouston3 @iteles The core functionality for this has now been completed. 🎉  PR can be found here - https://github.com/cul-2016/quiz/pull/336 **not ready** as I still need to complete a couple of things. 👍 

Lecturers are able to:
- Add
- Edit
- Run a Survey
Students are able to:
- Enter a Survey
- Respond to Survey Questions

I think the last thing to tackle is:
- [ ] the ability to see quiz History for a survey. 
I plan to tackle it tomorrow :) 

Quick update on timings for this issue, originally scoped for 3 Days, I technically started working on it on Late Thursday/Friday, but spent most of the day trying to fix the merge conflicts from the existing codebase that Franz had worked on. Took me Monday & Tuesday to do all the above functionality, plus some time tomorrow to finish off the final piece of work.

**Comment by shouston3** [comment]
Absolutely amazing work @sohilpandya

**Comment by sohilpandya** [comment]
**update**

- `Show Quiz Members`
  - updated `get-quiz-members` now takes `isSurvey` to return correct data from backend.

**Comment by iteles** [comment]
This was merged in and the linked user story functionality tested and verified by our product owner.
