### ISSUE TITLE
Application re-styling

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#339]
Based on @harrygfox's designs, we will be re-styling the application.

4 days have been reserved for this.

More information to be added as required.

---------------

- [x] Dashboard #356 
- [x] Quiz #358 
- [x] Performance Page #363 
- [x] Student holding-page for live-quiz #370 
- [x] questions for live-quiz #373 
- [x] Student result #383 
- [x] Lecturer add module #385 
- [x] Lecturer leaderboard #388 
- [x] Add Quiz/Survey #419
