### ISSUE TITLE
Quiz CSS

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#358]
Currently looks like: 
![screen shot 2017-01-20 at 15 17 10](https://cloud.githubusercontent.com/assets/2305591/22154467/930c6eca-df23-11e6-85d4-49466e0f97eb.png)

**TODO:**
- [x] Spacing issues
- [x] Removing bottom text
- [x] Fetch quiz data
- [x] arror icons(font awesome) and also medal/trophies images
- [ ] adding a new button class for disabled join live quiz button and also adding the radio button

**Comment by sohilpandya** [comment]
**update**

We are now fetching and displaying the correct data.

**Comment by sohilpandya** [comment]
**update**
The page now looks like this. very close to the wireframes. 
![screen shot 2017-01-23 at 14 43 58](https://cloud.githubusercontent.com/assets/2305591/22208358/80c7f870-e17a-11e6-8ea8-9df96e627211.png)

**Comment by iteles** [comment]
Closing this technical issue as complete 👍
