### ISSUE TITLE
Further CSS Styling

### ISSUE THREAD

**Issue by sohilpandya** [cul-2016/quiz#421]
Here are the remaining screens that require CSS:
- [x] Login Screen for lecturer **T4h** #437 
- [x] Register (lecturer screen) **T1h** #437
- [x] Forgotten Password (including message screen) **T2h** #437
- [x] Reset Password (including message screen) **T1h** #437
- [x] Dashboard (lecturer screen) **T2h** #438
- [x] Module Details page (lecturer screen - without leaderboard) **T4h** 
  - remove trophies from the view
  - #404 
- [x] Lecturer Members screen (module members details) - T6h #429 
- [x] Quiz Details - (includes view for quiz review) **T6h** #433 
- [x] Student module view (changing live quiz button to harry's designs) **T1h**
- [x] Hide Trophies from Student module view **T25h**
- [x] Leaderboard CSS increase font size #388 **T25m**
- [x] Hide is-Last-Quiz from add new-quiz
- [x] #383 address comments by Stian

**Total 4 days**

**Comment by sohilpandya** [comment]
Completely forgot about the Edit-quiz/survey styling, This has now been addressed.

**Comment by iteles** [comment]
Great! Closing as all linked issues have now been closed by product owner 👍
