### ISSUE TITLE
Remaining small changes

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#449]
These are small changes that would be good to see - @sohilpandya could you estimate time for each of these to see how best to use remaining time?

- [x] Realign login and register pages to sit centrally vertically on desktop browsers (#437)
- [x] Bronze medal for 0% on student end-of-survey page (#383)
- [x] Separate tabs for student scores and questions on lecturer review quiz page (#448)
- [x] Alert before deleting student (#429)
- [x] Close expanded student view (#429)
- [x] Edit Survey Does Not Save Changes #450

**Comment by sohilpandya** [comment]
Hi Stian, thanks again for raising the issue. 

Here are my time estimates for the above issues:
- #437 **T25min**
- #383 **Done**
- #448 Add a button which would take the lecturer to a review questions screen **T1h**
- #449 Alert box before deleting a student and adding a close button to close the expanded student view **T3h**

Total: **~1/2 Day**

Please let me know if you would like me to work on the issues above, I can plan to spend half a day tomorrow to complete the issues you've listed above. 

Thanks

**Comment by stianr** [comment]
Thanks @sohilpandya - very helpful. Just let me talk to Ines about remaining time so we can prioritise - I'm guessing this is less urgent if you're not planning on working on it today.

**Comment by stianr** [comment]
Have heard back from Ines - please do all of these, plus the bug fixing in #450.

**Comment by sohilpandya** [comment]
@stianr the above changes are ready to be tested out by you on staging. 

Thanks.

**Comment by stianr** [comment]
This all looks great – haven’t been able to test extensively as I’m away, but looks good. Given timings now (we’re going into the fourth week of term and I have two lecture classes it’s being run in this week), we should deploy it so that it’s ready for use. I can then give feedback at the end of the week on how it’s gone, and any issues.
