### ISSUE TITLE
Superuser data management

### ISSUE THREAD

**Issue by jackcarlisle** [cul-2016/quiz#464]
@stianr We'll be starting with this particular feature as it's the highest priority and it has the potential for taking a while. 

- [x] Create a super admin dashboard + give specific users access to this
- [x] View/delete any student or lecturer within the app #465 
- [x] Ability to download snapshot of entire database as CSV #466 
  - [x] CSV of full answer dataset
  - [x] CSV of full quiz question set

Total time estimate: 5 days
