### ISSUE TITLE
Final day Sprint 12 priorities

### ISSUE THREAD

**Issue by iteles** [cul-2016/quiz#697]
We have reserved the final day of sprint 12 for deployment and any emergent issues.

The list of activities for this day is currently as follows:
+ [ ] Keeping lecturer accounts from expiring https://github.com/cul-2016/quiz/issues/696
+ [ ] Making the changes requested in QA to the forum work
+ [x] Having a call with ViaDynamics to take them through the application architecture
+ [ ] Enhancing the documentation to make sure ViaDynamics are able to maintain the application with some ease
+ [ ] Deployment to production once you have finished testing and given the green light
+ [ ] Discussing status of load testing issue #553

**Comment by stianr** [comment]
Thanks for the helpful list @iteles. I'll need to look at and test the forum before we prioritise the remaining time. Is it possible to get that deployed to the staging area sometime soon? (Or if it's already active, point me in the right direction?)

**Comment by stianr** [comment]
If we can use a bit of the final day straight away to update #701 before it starts leading to confused emails from students and lecturers, that would be great.

**Comment by stianr** [comment]
We seem to have around half a day left, so the priorities are for having a fully functional version of the basic quodl to showcase to this year's lecturers and student. 

- [ ] #698 correcting all email links to point to URLs that are under www,quodl.co.uk not the current cul-app.herokuapp,com. (I've already had to troubleshoot issues with one lecturer who ended up on the cul-app.herokuapp.com version of the site and got stuck in login failure loop.) This is urgent as it will lead to all sorts of problems if 220 students start following links to the cul-app version and then don't understand why they can't log in. 
- [ ] #701 correcting the information re badges
- [ ] Making links to study planner and forum really small and adding '[Coming soon]' to them so it's clear they're not current.
- [ ] #696 Keeping lecturer accounts from expiring 

Any remaining time to be used for a discussion about GDPR compliance.

**Comment by stianr** [comment]
Also just checking that #662 has been implemented. On the big-class test with 215 students today, around half a dozen signed up for lecturer accounts, which caused disruption, so definitely something we need to deploy.

**Comment by stianr** [comment]
Now updated in #704, so closing this.
