### ISSUE TITLE
Final issues for end of Sprint 12

### ISSUE THREAD

**Issue by stianr** [cul-2016/quiz#704]
As we've moved on a bit since opening #697, I'm closing that and creating this for the current priority issues

- [ ] Fixing badge criteria bug #701 
- [ ] Investigating IE11 bug and fixing if easy #702
- [ ] Briefly discussing load given testing results and in-lecture use #553 
- [ ] Keeping lecturer accounts from expiring #696
- [ ] Discussing GDPR compliance and updating privacy statement and flow where necessary #699
- [ ] Deployment to production

There were also the following in the previous version:

- [ ] Making the changes requested in QA to the forum work
- [ ] Enhancing the documentation to make sure ViaDynamics are able to maintain the application with some ease
